
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Enumeration;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;

/**
 * The configuration screen.
 * This screen allows the user to setup the game.
 * 
 * @author Four Guys and a Mann
 * @version v1.1 11/9/11
 */
public class configScreen extends javax.swing.JPanel {

    private ButtonListener listen;

    /** Creates new form configScreen */
    public configScreen(GameInterface face) {
        initComponents();

        listen = new ButtonListener(face);
        begin.addActionListener(listen);

        this.setBackground(Color.yellow);
        banker.setBackground(Color.yellow);
        carpenter.setBackground(Color.yellow);
        farmer.setBackground(Color.yellow);

        leisurely.setBackground(Color.yellow);
        steady.setBackground(Color.yellow);
        grueling.setBackground(Color.yellow);

        barebones.setBackground(Color.yellow);
        meager.setBackground(Color.yellow);
        filling.setBackground(Color.yellow);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {

        professions = new javax.swing.ButtonGroup();
        pace = new javax.swing.ButtonGroup();
        rations = new javax.swing.ButtonGroup();
        leader = new javax.swing.JLabel();
        leaderName = new javax.swing.JTextField();
        professionText = new javax.swing.JLabel();
        banker = new javax.swing.JRadioButton();
        carpenter = new javax.swing.JRadioButton();
        farmer = new javax.swing.JRadioButton();
        paceText = new javax.swing.JLabel();
        leisurely = new javax.swing.JRadioButton();
        steady = new javax.swing.JRadioButton();
        grueling = new javax.swing.JRadioButton();
        rationText = new javax.swing.JLabel();
        barebones = new javax.swing.JRadioButton();
        meager = new javax.swing.JRadioButton();
        filling = new javax.swing.JRadioButton();
        oregonTrail = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        member1Label = new javax.swing.JLabel();
        member2Labe = new javax.swing.JLabel();
        member3Label = new javax.swing.JLabel();
        member4Label = new javax.swing.JLabel();
        member1 = new javax.swing.JTextField();
        member2 = new javax.swing.JTextField();
        member3 = new javax.swing.JTextField();
        member4 = new javax.swing.JTextField();
        partyMembersLabel = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        begin = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(650, 323));

        leader.setText("Leader Name:");

        professionText.setText("Profession:");

        professions.add(banker);
        banker.setText("Banker");

        professions.add(carpenter);
        carpenter.setText("Carpenter");

        professions.add(farmer);
        farmer.setText("Farmer");

        paceText.setText("Pace:");

        pace.add(leisurely);
        leisurely.setText("Leisurely");

        pace.add(steady);
        steady.setText("Steady");

        pace.add(grueling);
        grueling.setText("Grueling");

        rationText.setText("Rations:");

        rations.add(barebones);
        barebones.setText("Bare Bones");

        rations.add(meager);
        meager.setText("Meager");

        rations.add(filling);
        filling.setText("Filling");

        oregonTrail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        oregonTrail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/configurationScreen/resources/oregon_trail_25 - Copy.gif"))); // NOI18N

        member1Label.setText("Member 1:");

        member2Labe.setText("Member 2:");

        member3Label.setText("Member 3:");

        member4Label.setText("Member 4:");

        partyMembersLabel.setText("Party Members:");

        begin.setText("Begin Journey!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(leader)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(leaderName, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(partyMembersLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(member1Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(member1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(member2Labe)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(member2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(member3Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(member3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(member4Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(member4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(oregonTrail))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(professionText)
                            .addComponent(banker)
                            .addComponent(carpenter)
                            .addComponent(farmer))
                        .addGap(112, 112, 112)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(leisurely)
                            .addComponent(steady)
                            .addComponent(grueling)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(paceText)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rationText)
                            .addComponent(barebones)
                            .addComponent(meager)
                            .addComponent(filling)))
                    .addComponent(begin, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(leader))
                            .addComponent(leaderName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addComponent(partyMembersLabel)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(member1Label))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(member1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(member2Labe))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(member2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(member3Label))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(member3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(member4Label))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(member4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(oregonTrail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(professionText)
                            .addComponent(paceText)
                            .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(banker)
                                .addComponent(carpenter)
                                .addComponent(farmer))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(leisurely)
                                .addComponent(steady)
                                .addComponent(grueling))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rationText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(barebones)
                        .addComponent(meager)
                        .addComponent(filling)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(begin)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton banker;
    private javax.swing.JRadioButton barebones;
    private javax.swing.JButton begin;
    private javax.swing.JRadioButton carpenter;
    private javax.swing.JRadioButton farmer;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JRadioButton filling;
    private javax.swing.JRadioButton grueling;
    private javax.swing.JLabel leader;
    private javax.swing.JTextField leaderName;
    private javax.swing.JRadioButton leisurely;
    private javax.swing.JRadioButton meager;
    private javax.swing.JTextField member1;
    private javax.swing.JLabel member1Label;
    private javax.swing.JTextField member2;
    private javax.swing.JLabel member2Labe;
    private javax.swing.JTextField member3;
    private javax.swing.JLabel member3Label;
    private javax.swing.JTextField member4;
    private javax.swing.JLabel member4Label;
    private javax.swing.JLabel oregonTrail;
    private javax.swing.ButtonGroup pace;
    private javax.swing.JLabel paceText;
    private javax.swing.JLabel partyMembersLabel;
    private javax.swing.JLabel professionText;
    private javax.swing.ButtonGroup professions;
    private javax.swing.JLabel rationText;
    private javax.swing.ButtonGroup rations;
    private javax.swing.JRadioButton steady;
    // End of variables declaration//GEN-END:variables

    // This method returns the selected radio button in a button group
    public static JRadioButton getSelection(ButtonGroup group) {
        for (Enumeration e = group.getElements(); e.hasMoreElements();) {
            JRadioButton b = (JRadioButton) e.nextElement();
            if (b.getModel() == group.getSelection()) {
                return b;
            }
        }
        return null;
    }

    private class ButtonListener implements ActionListener {

        GameInterface game;
        Wagon wagon;
        Leader l;

        public ButtonListener(GameInterface face) {
            this.game = face;
        }

        public void actionPerformed(ActionEvent event) {

            boolean changeScreen = true;
            boolean alreadyError = false;

            if (alreadyError == true) {
            } else if (leaderName.getText().equals("")) {
                JOptionPane.showMessageDialog(game, "Please enter your name", "Error", JOptionPane.ERROR_MESSAGE);
                changeScreen = false;
                alreadyError = true;
            }
            if (alreadyError == true) {
            } else if (member1.getText().equals("") || member2.getText().equals("") || member3.getText().equals("") || member4.getText().equals("")) {
                JOptionPane.showMessageDialog(game, "You must have four other people traveling with you", "Error", JOptionPane.ERROR_MESSAGE);
                changeScreen = false;
                alreadyError = true;
            }
            if (alreadyError == true) {
            } else if (getSelection(professions) == (null)) {
                JOptionPane.showMessageDialog(game, "Please select a profession", "Error", JOptionPane.ERROR_MESSAGE);
                changeScreen = false;
                alreadyError = true;
            } else {
                String p = getSelection(professions).getText();
                if (p.equals("Banker")) {
                	l = new Leader(leaderName.getText(), Profession.Banker);
                } else if (p.equals("Carpenter")) {
                    l = new Leader(leaderName.getText(), Profession.Carpenter);
                } else {
                    l =new Leader(leaderName.getText(), Profession.Farmer);
                }
            }

            ArrayList<Member> members = new ArrayList<Member>();
            members.add(new Member(member1.getText()));
            members.add(new Member(member2.getText()));
            members.add(new Member(member3.getText()));
            members.add(new Member(member4.getText()));
            wagon = new Wagon(l, members);

            

            if (alreadyError == true) {
            } else if (getSelection(pace) == (null)) {
                JOptionPane.showMessageDialog(game, "Please select a pace", "Error", JOptionPane.ERROR_MESSAGE);
                changeScreen = false;
                alreadyError = true;
            } else {
                String pa = getSelection(pace).getText();
                if (pa.equals("Leisurely")) {
                    wagon.setCurrPace(Pace.Leisurely);
                } else if (pa.equals("Steady")) {
                    wagon.setCurrPace(Pace.Steady);
                } else {
                    wagon.setCurrPace(Pace.Grueling);
                }
            }
            if (alreadyError == true) {
            } else if (getSelection(rations) == (null)) {
                JOptionPane.showMessageDialog(game, "Please select a rations", "Error", JOptionPane.ERROR_MESSAGE);
                changeScreen = false;
                alreadyError = true;
            } else {

                String r = getSelection(rations).getText();
                if (r.equals("Bare Bones")) {
                    wagon.setCurrRations(Rations.BareBones);
                } else if (r.equals("Meager")) {
                    wagon.setCurrRations(Rations.Meager);
                } else {
                	wagon.setCurrRations(Rations.Filling);
                }
            }
            
            game.setWagon(wagon);
            game.setMap(new Map(wagon));

            if (changeScreen == true) {
                Shop shop = new Shop();
                JPanel panel = new generalStore(shop, game);
                panel.setSize(new Dimension(450, 300));
                game.updateBounds(panel.getWidth(), panel.getHeight());
                game.changeDisplay(panel);
            }
        }
    }
}
